### PR TITLE
fix month slider bug

### LINKED ISSUE #241: Month Slider on screen-2 set months to 0 at 70yo but does not revert when changing retirement year
This issue is related to the new month slider added as part of pull request #230.

See example screencast below:

ezgif com-gif-maker

### PR DESCRIPTION
**Pull request by changangus**
I set it up to default to zero when the year slider is on 70, once the user changes the year it stays on zero but when it changes it updates.

closes #241

### CODE REVIEW

**Comment by dmeegan** [comment]
@changangus looks good to me! I don't have the permissions to merge PR's, but it will probably be merged at the weekly hack night.

**Comment by dmeegan** [comment]
@changangus also if you could add a note on your PR similar to how Matan did in the screenshot below where he says "closes #xxx" referring to the issue that I assigned to you, it will automatically close the issue when your PR is merged into the main branch.

image

**Comment by changangus** [comment]
Sounds good! I'll do that now.

**Review by thadk — APPROVED** [review]
Mob programming to review it: even other edge cases work better with onChange prop

**Pull request merged**
