### PR TITLE
Minor edits, issue numbers in comments

### LINKED ISSUE #125: Change text: Please enter the amount of your *monthly* pension or lump sum
Add "Monthly" to the Step 3 question: "Please enter the amount of your pension of lump sum.

### PR DESCRIPTION
**Pull request by pnaduthota**
Closed #125, #131, #114, #132 ,#126

### CODE REVIEW

**Comment by pnaduthota** [comment]
Closes #131

**Comment by pnaduthota** [comment]
Closed #114

**Comment by thadk** [comment]
Is this good enough to close #124, @annemeeker 
image

**Comment by thadk** [comment]
Oops, I noticed removing Nick's `getFullRetirementDate` breaks the print page, specifically this line `      userFRD: parsedProfile["RawData"]["userFullRetireDate"],` which uses it behind the scenes.

**Pull request merged**
