### PR TITLE
Add the ability to try out different retirement dates

### PR DESCRIPTION
**Pull request by sw9**
Add a slider to the results page so users can try out difference retirement dates.

Refactor the performCalc function so that it can be used for both the initial result computation as well as adjusted retirement date computations.

### CODE REVIEW

**Comment by sw9** [comment]
Note that there is a purposeful deviation from the design in windfall_almedits_20191029.pdf.
In that mockup, the predicted results are shown in input boxes for some reason. I think it is confusing to show output styled in the same manner as input. Thus, I kept the previous approach of just wrapping the output in ```<strong><code>```.

**Comment by thadk** [comment]
Nice job on the interactivity! 

1.  Can you please add more padding above and below the slider, and maybe widen the draggable item?
2.  I think we should start the slider at the same year of retirement that they picked with the date pickers.

Also this has drawn my attention to the calculation no longer being accurate to the latest text (see difference between the Observable and ). Besides any known issue with `getAIMEFromEarnings()` indexing year subtraction, I don't think we are actually calculating "Monthly benefit at full retirement age" – we'd have to lookup the NormalRetirementAge in fractional years and put that in the calculator. 

With that change, the value under the top text will be different because that'll be the looked up one. It wouldn't reflect the date the person said at all. We can do this in another issue, it isn't critical for tomorrow.

image

image

**Comment by thadk** [comment]
On mobile for some reason it seems to give different values. Touch drag does work though!

**Comment by thadk** [comment]
On mobile touch works great.

**Comment by sw9** [comment]
The ui issues you raised have been fixed. There definitely are issues with how the observable library is used though. I noticed for example that userWEP isn't even getting passed in.

Also, the results page breaks entirely in some cases that I haven't pinned down yet. Seems to happen when I adjust the retirement date to be further in the future. But such bugs would be out of the scope of this pull request.

**Pull request merged**
