### PR TITLE
Hook refactor prescreen-1d

### PR DESCRIPTION
**Pull request by dylanesque**
Refactored this component to use a functional component rather than a class component.

### CODE REVIEW

**Comment by thadk** [comment]
@dylanesque Nice job on this first pass! I haven't had a chance to run it yet but do have one early comment on code review:

I looked closer at the example I suggested for you from https://github.com/codeforboston/windfall-elimination/blob/develop/src/pages/screen-2a.tsx and I realized that one house-cleaning tweak relevant here got lost in the mob programming. Thanks for patience. 

You already cleaned up some of it (i.e. `FunctionComponent`). Basically because we're now able to have the `useUserState()` and `useUserStateActions()` in the main function to access the two contexts, we no longer need [the class component prop wrapper](https://github.com/codeforboston/windfall-elimination/pull/251/files#diff-855cb7d4c98c96c379c1db5a283e729207fc6f04e05dfd845763b8ed1053424bR250-R253) or its fancy [typed interface syntax for the props](https://github.com/codeforboston/windfall-elimination/pull/251/files#diff-855cb7d4c98c96c379c1db5a283e729207fc6f04e05dfd845763b8ed1053424bR76). 

If I recall right, I think our lost solution in the mob programming session for `screen-2a.tsx` was just to remove the two context-based props (userState, userStateActions) and all the uses of `Prescreen1dProps` interface. You might need to try a few things though if my memory is failing me. Feel free to bring it on Tuesday if it doesn't work as easily as I think.

If you get a chance, in another PR to `develop` branch, feel free to make these changes in `screen-2a.tsx` as well, tidying up as necessary, so we have two clean examples of hooks pages once both merged.

**Comment by thadk** [comment]
This is significant progress on #135

**Comment by dylanesque** [comment]
That all tracks:: I tested it briefly and it compiled just fine and didn't throw any errors, but didn't really stress-test the changed section. I'll implement your notes, and take a closer look.

**Comment by thadk** [comment]
@dylanesque Thanks again, Mike. Your code is now live but behind the feature hook until we finish that page. I will use it as an example for other people to convert pages to hooks. 

Anyway, your code shows when you run develop branch with `GATSBY_SHOW_FUTURE_EARNINGS_PAGE=true npm start`

**Pull request merged**
