### PR TITLE
added title to year-to-year earning, row counts, fixed table sty…

### PR DESCRIPTION
**Pull request by olena-ageyeva**
(also starts using placeholders instead of "0" in the manual entry and normal table entry to avoid users needing to erase the "0" -tk)

### CODE REVIEW

**Comment by thadk** [comment]
Please add the glossary piece and either remove the "from" or add the filename. Thanks again, Olena!

**Comment by olena-ageyeva** [comment]
Hi Thad!
Just submitted additions to my pull request; added file name to a table title - had to add a param to FileUpload Component state to extract that data at the table level . A bit unsure about glossary - I placed it next to table with css. Could not figure out any other way. 
Hope to connect soon. Thanks!

**Comment by thadk** [comment]
The glossary looks good but there is still the hanging "from":
image

**Comment by olena-ageyeva** [comment]
Hi Thad! I see what you mean. Fixed that. File name does not display new when it's unknown. Could you please let me know if this works.

**Pull request merged**
