### PR TITLE
FileUpload / Reorder tabbing on forms

### PR DESCRIPTION
**Pull request by thadk**
Reorder tabbing on form tables for accessibility
View form tables at /prescreen-1b/ by selecting "no" for "Do you have a MySocialSecurity account?"

from @alexjcode
https://github.com/misspran/windfall-elimination/pull/2/commits

### CODE REVIEW

**Comment by sw9** [comment]
the manual table is still broken in this version. also, the questions still don't match the design in  windfall_almedits_20191015.pdf. Basically, harlan's design calls for a more extensive reworking of this screen.

**Comment by sw9** [comment]
okay, I was confused about your comment @thadk but after looking at the commit, it looks like it's actually fixing the tabbing on the manual form. which looks good to me.

**Comment by thadk** [comment]
> okay, I was confused about your comment @thadk but after looking at the commit, it looks like it's actually fixing the tabbing on the manual form. which looks good to me.

Yep, I was just making sure we didn't lose this which was in Vi's repository. It can be merged around the same time as the fix for the manual form. Sorry for the confusion.

**Comment by sw9** [comment]
I think this can be merged in now.

**Pull request merged**
