### PR TITLE
Removed z-index from footer

### PR DESCRIPTION
**Pull request by dylanesque**
-Removed z-index from Footer element.

-Added `overflow-x: hidden` to global layout stylesheet

### CODE REVIEW

**Comment by sw9** [comment]
The issue I reported initially is fixed. However, after this change, I seem to no longer be able to scroll left to right on mobile. This is kinda a problem since our ui is pretty wide (left sidebar takes up a lot of the space).

**Comment by dylanesque** [comment]
YMMV since my design training is pretty catch as catch can, But I don't think that "it's the desktop version, but you have to scroll across" is the ideal mobile experience. I'm curious as to what Harlan, Anne, etc think about this.

**Comment by thadk** [comment]
@dylanesque Please add a 

`@media screen and (min-width: 30em) ` around the hidden-x so it does not affect mobile screens. We will try to have this for Saturday.

**Comment by thadk** [comment]
@dylanesque thanks so much! I just saw this.

**Comment by thadk** [comment]
image
Why didn't we like the position:fixed? I think it is fantastic the action is visible no matter how small the user's screen is. @sw9 @dylanesque

**Comment by dylanesque** [comment]
I wish I had a better answer than "I made this change because it had the desired effect", but I don't have anything more articulate than that given how long ago this was.  I will say that I didn't understand what we were getting out of `absolute` positioning, especially since this codebase is mostly using flexbox and other modern techniques.

**Pull request merged**
