### PR TITLE
added table for screen-2a

### PR DESCRIPTION
**Pull request by linesbetween**
Progress on #141
Next: 
animate bar charts

### CODE REVIEW

**Comment by thadk** [comment]
I noticed our tests are failing with `79:21  error  React Hook "useUserState" is called in function "renderSections" that is neither a React function component nor a custom React Hook function. React component names must start with an uppercase letter  react-hooks/rules-of-hooks`

This is because the `renderSections` is a function component and should start with a capital letter. I think we can fix the test by changing it to `SliderSections` everywhere it is used.

**Comment by thadk** [comment]
Hi Faye, a few more small things to match the design and we can merge this in.
- [ ] Please add this at the bottom of Step 1:

```
However, if you answered “Yes” to the first question in the “Employment Status” section of this website, the amount you get back of this first bucket will be different. To learn more, please see the <a href="https://www.ssa.gov/pubs/EN-05-10045.pdf">Windfall Elimination Provision pamphlet</a>
```

- [ ] Please add this spanning header to the table:

image

- [ ] For the other pages please add this other spanning header to the table:
image

- [ ] Also please put a space between "step" and the number.

- [ ] Please fix the text in the Step 4:
`Remember: this is the basic amount you are paid before Social Security adjusts your benefits lower for early retirement, or higher for delayed retirement.` (I think there was a typo on the word "paid".

- [ ] Finally please add a final page like this (with links):
image

```
Commonly Asked Questions

I currently have an overpayment, so what should I do?
<a href="https://www.ssa.gov/pubs/EN-05-10098.pdf">See the SSA document on Overpayments</a>

How can I work on changing this law? 
<a href="https://www.house.gov/representatives/find-your-representative">Find your Representative</a>

How can I talk with my representative about Social Security?
<a href="https://casework.civicapp.us/casework/">Request for your Representative's staff to look at your case</a>
```

**Comment by dmeegan** [comment]
One thing small thing that I realized. I believe we were dynamically setting the height of the top and bottom divs of the chart when we would only need to set the bottom one. 

Using flexbox we can set the top div to grow or shrink to fill the remaining space of the container. 

What we did is not wrong, but we could clean up the code by not setting the height of both divs.

**Review by thadk — APPROVED** [review]
Thanks so much, looks great at every step.

**Pull request merged**
