### PR TITLE
Updated datepicker

### PR DESCRIPTION
**Pull request by pnaduthota**
- Updated npm package from **react-datepicker** to **react-date-picker**
- Updated min width
- Set calendar default to open to year
- Got rid of date

closes #107

### CODE REVIEW

**Comment by sw9** [comment]
I like the new datepicker, the ability to go decade by decade. But some concerns:
1. The previous datepicker had month, day, year. Can we bring this back? Having month/year is kinda confusing as a way to enter dates.
2. The previous datepicker did some things to ensure that retire date is always at least 18 years after dob. For example, the retire date picker was disabled until a dob was set for example. If you moved your dob back, the retire date was also moved back. The retire date was also limited in that you could not select a retire date less than 18 years after your dob.
3. Can the clear date button be removed? These are required fields. I see no reason to have the ability to clear these dates.
4. Previously, dob opened by default to 62 years or something like that before the current time. And the retire date picker opened by default to 62 years after whatever dob you set.

I'm fine if you feel like some of this logic is unnecessary. But would like your thoughts in any case.

**Comment by thadk** [comment]
It would be great to have this in by Saturday. The main other issue I noticed was that:
* the picker that appears when you click to start typing doesn't respond to clicks (if there is a config option, I don't think we really need this)
* but the picker that appears when you click on the little calendar icon works well.

**Comment by pnaduthota** [comment]
@sw9 to address your questions:

1. This datepicker (documentation [here](https://www.npmjs.com/package/react-datepicker)) does not use day, but if you think about it, nobody really thinks in their specific retire date, but more their retirement year or month. For example, if I asked you right now when you expected to retire, I expect you'd answer in year, as opposed to day, If it doesn't affect the calculator I don't think we need it.
2. Makes sense, will look into it.
3. Also makes sense, though I think this got addressed somewhere.
4. Don't think we have an end date anymore but I'll look into it as well.

@thadk working on it today, should have something tonight.

**Comment by thadk** [comment]
Oops, accidentally wiped out commit history with rebase. 

But hmm, the Firefox problem with the highlight-input-clicks-unrecognized still persists, even with new versions.

The issue is already reported here: `https://github.com/wojtekmaj/react-date-picker/issues/175`

**Comment by thadk** [comment]
I think for birthdate it makes sense to ask for the date after all.

**Pull request closed without merging**
